// AUTO-GENERATED by scripts/extract-faces.mjs from
// "docs/design/WHO Face System.html". Do not edit by hand — re-run the script.
// Each value is the inner SVG markup of a part, drawn ink-on-transparent on the
// shared 0 0 200 200 grid. The head is one path whose fill is set at render time.

export const HEAD_PATH =
  "M100 8c46-2 88 40 92 88 4 50-38 96-90 96S6 152 8 98C10 50 52 10 98 8";

export const EYES: Record<string, string> = {
  "eyes-01": "<g fill=\"none\" stroke=\"#201D18\" stroke-width=\"9\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M68 63c13 0 20 9 20 19s-8 19-20 19-20-9-20-19 8-19 20-19\"></path><path d=\"M132 63c13 0 20 9 20 19s-8 19-20 19-20-9-20-19 8-19 20-19\"></path></g><g fill=\"#201D18\" stroke=\"none\"><circle cx=\"70\" cy=\"85\" r=\"6.5\"></circle><circle cx=\"134\" cy=\"85\" r=\"6.5\"></circle></g>",
  "eyes-02": "<g fill=\"none\" stroke=\"#201D18\" stroke-width=\"9\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M48 84c8-11 32-11 40 0\"></path><path d=\"M48 84c9 10 31 10 40 0\"></path><path d=\"M112 84c8-11 32-11 40 0\"></path><path d=\"M112 84c9 10 31 10 40 0\"></path><path d=\"M50 62c10-6 24-7 34-3\"></path><path d=\"M114 59c10-4 25-2 34 4\"></path></g><g fill=\"#201D18\" stroke=\"none\"><circle cx=\"82\" cy=\"84\" r=\"6\"></circle><circle cx=\"146\" cy=\"84\" r=\"6\"></circle></g>",
  "eyes-03": "<g fill=\"none\" stroke=\"#201D18\" stroke-width=\"9\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M47 80c9 13 32 13 41 0\"></path><path d=\"M45 76c14-5 30-4 44 1\"></path><path d=\"M111 80c9 13 32 13 41 0\"></path><path d=\"M109 76c14-5 30-4 44 1\"></path></g><g fill=\"#201D18\" stroke=\"none\"><circle cx=\"68\" cy=\"86\" r=\"5\"></circle><circle cx=\"132\" cy=\"86\" r=\"5\"></circle></g>",
  "eyes-04": "<g fill=\"#201D18\" stroke=\"none\"><circle cx=\"63\" cy=\"84\" r=\"8\"></circle><circle cx=\"127\" cy=\"84\" r=\"8\"></circle></g><g fill=\"none\" stroke=\"#201D18\" stroke-width=\"9\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M50 61c11-7 25-6 35 1\"></path><path d=\"M114 62c11-7 25-6 35 1\"></path></g>",
  "eyes-05": "<g fill=\"none\" stroke=\"#201D18\" stroke-width=\"9\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M68 62c14 0 22 9 22 20s-9 20-22 20-22-9-22-20 9-20 22-20\"></path><path d=\"M132 62c14 0 22 9 22 20s-9 20-22 20-22-9-22-20 9-20 22-20\"></path></g><g fill=\"#201D18\" stroke=\"none\"><circle cx=\"68\" cy=\"82\" r=\"10\"></circle><circle cx=\"132\" cy=\"82\" r=\"10\"></circle></g><g fill=\"none\" stroke=\"#201D18\" stroke-width=\"9\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M46 50c13 3 26 6 36 12\"></path><path d=\"M154 50c-13 3-26 6-36 12\"></path></g>",
  "eyes-06": "<g fill=\"none\" stroke=\"#201D18\" stroke-width=\"9\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M47 90c6-16 34-16 41 0\"></path><path d=\"M111 90c6-16 34-16 41 0\"></path></g>",
  "eyes-07": "<g fill=\"none\" stroke=\"#201D18\" stroke-width=\"7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M68 84a5 5 0 1 1 6 4 11 11 0 1 1-13-8 17 17 0 1 1 20 14\"></path><path d=\"M132 84a5 5 0 1 1 6 4 11 11 0 1 1-13-8 17 17 0 1 1 20 14\"></path></g>",
  "eyes-08": "<g fill=\"#201D18\" stroke=\"none\"><circle cx=\"68\" cy=\"85\" r=\"8\"></circle><circle cx=\"132\" cy=\"85\" r=\"8\"></circle></g><g fill=\"none\" stroke=\"#201D18\" stroke-width=\"9\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M49 51c11-8 27-7 37 2\"></path><path d=\"M113 64c12-3 25-3 36 1\"></path></g>",
  "eyes-09": "<g fill=\"none\" stroke=\"#201D18\" stroke-width=\"9\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M46 70h40c3 0 4 2 4 5v18c0 3-2 5-5 5H48c-3 0-4-2-4-5V75c0-3 1-5 2-5\"></path><path d=\"M114 70h40c3 0 4 2 4 5v18c0 3-2 5-5 5h-37c-3 0-4-2-4-5V75c0-3 1-5 2-5\"></path><path d=\"M90 80c5-3 14-3 24 1\"></path></g><g fill=\"#201D18\" stroke=\"none\"><circle cx=\"68\" cy=\"85\" r=\"6\"></circle><circle cx=\"132\" cy=\"85\" r=\"6\"></circle></g>",
  "eyes-10": "<g fill=\"#201D18\" stroke=\"none\"><circle cx=\"82\" cy=\"86\" r=\"5.5\"></circle><circle cx=\"120\" cy=\"86\" r=\"5.5\"></circle></g><g fill=\"none\" stroke=\"#201D18\" stroke-width=\"9\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M60 58c11-9 26-8 36 3\"></path><path d=\"M106 61c11-11 26-12 37-3\"></path></g>",
};

export const MOUTHS: Record<string, string> = {
  "mouth-01": "<g fill=\"none\" stroke=\"#201D18\" stroke-width=\"9\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M76 143c9 3 18-3 26-1 8 2 14 4 22 1\"></path></g>",
  "mouth-02": "<g fill=\"none\" stroke=\"#201D18\" stroke-width=\"9\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M74 150c14 4 30 1 48-14\"></path><path d=\"M122 136c4 0 6 3 6 7\"></path></g>",
  "mouth-03": "<g fill=\"none\" stroke=\"#201D18\" stroke-width=\"9\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M100 124c13 0 20 8 20 19s-8 20-20 20-20-9-20-20 8-19 20-19\"></path></g>",
  "mouth-04": "<g fill=\"none\" stroke=\"#201D18\" stroke-width=\"9\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M74 131h52c3 0 4 2 4 5v13c0 3-2 5-5 5H75c-3 0-4-2-4-5v-13c0-3 1-5 3-5\"></path><path d=\"M88 132v20M100 132v20M113 132v20\"></path></g>",
  "mouth-05": "<g fill=\"none\" stroke=\"#201D18\" stroke-width=\"9\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M76 136c7 14 41 14 48 0\"></path></g>",
  "mouth-06": "<g fill=\"none\" stroke=\"#201D18\" stroke-width=\"9\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M76 152c7-15 41-15 48 0\"></path></g>",
  "mouth-07": "<g fill=\"none\" stroke=\"#201D18\" stroke-width=\"9\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M76 136c7 13 41 13 48-1\"></path><path d=\"M104 148c8-2 14 3 13 10-1 6-8 9-13 6-4-2-5-8-3-13\"></path></g>",
  "mouth-08": "<g fill=\"none\" stroke=\"#201D18\" stroke-width=\"9\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M74 144c10 2 20-2 28-1 8 1 15 3 24 0\"></path></g><g fill=\"none\" stroke=\"#201D18\" stroke-width=\"7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M86 136v16M100 135v16M114 136v16\"></path></g>",
  "mouth-09": "<g fill=\"none\" stroke=\"#201D18\" stroke-width=\"9\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M73 137c8 12 15-2 24 4 8 6 17 12 28-4\"></path></g>",
  "mouth-10": "<g fill=\"none\" stroke=\"#201D18\" stroke-width=\"9\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M100 132c9 0 14 5 14 12s-6 12-14 12-14-5-14-12 6-12 14-12\"></path></g>",
};

export const MARKS: Record<string, string> = {
  "mark-00": "",
  "mark-01": "<g fill=\"#201D18\" stroke=\"none\"><circle cx=\"52\" cy=\"116\" r=\"4\"></circle><circle cx=\"64\" cy=\"124\" r=\"4\"></circle><circle cx=\"44\" cy=\"128\" r=\"4\"></circle><circle cx=\"148\" cy=\"116\" r=\"4\"></circle><circle cx=\"136\" cy=\"124\" r=\"4\"></circle><circle cx=\"156\" cy=\"128\" r=\"4\"></circle></g>",
  "mark-02": "<g fill=\"none\" stroke=\"#201D18\" stroke-width=\"7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M44 100c3 14 5 22 4 32\"></path><path d=\"M35 108c7 1 13 0 18-2\"></path><path d=\"M38 122c7 1 13 0 18-2\"></path></g>",
  "mark-03": "<g fill=\"#201D18\" stroke=\"none\"><circle cx=\"138\" cy=\"130\" r=\"5.5\"></circle></g>",
  "mark-04": "<g fill=\"none\" stroke=\"#201D18\" stroke-width=\"7\" stroke-linecap=\"round\" stroke-linejoin=\"round\" opacity=\"0.75\"><path d=\"M38 120l16 12M46 114l16 12M54 108l14 12M146 108l-14 12M154 114l-16 12M162 120l-16 12\"></path></g>",
  "mark-05": "<g fill=\"none\" stroke=\"#201D18\" stroke-width=\"7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M40 62l26-16c3-2 6-1 8 2l6 10c2 3 1 6-2 8l-26 16c-3 2-6 1-8-2l-6-10c-2-3-1-6 2-8\"></path><path d=\"M52 55l16-10M56 68l16-10\"></path></g>",
  "mark-06": "<g fill=\"#201D18\" stroke=\"none\" opacity=\"0.8\"><circle cx=\"70\" cy=\"164\" r=\"3.5\"></circle><circle cx=\"84\" cy=\"171\" r=\"3.5\"></circle><circle cx=\"100\" cy=\"174\" r=\"3.5\"></circle><circle cx=\"116\" cy=\"171\" r=\"3.5\"></circle><circle cx=\"130\" cy=\"164\" r=\"3.5\"></circle><circle cx=\"77\" cy=\"156\" r=\"3.5\"></circle><circle cx=\"123\" cy=\"156\" r=\"3.5\"></circle></g>",
  "mark-07": "<g fill=\"none\" stroke=\"#201D18\" stroke-width=\"7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M56 66l14-14\"></path></g>",
  "mark-08": "<g fill=\"none\" stroke=\"#201D18\" stroke-width=\"7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M140 108c5 5 8 9 8 14 0 4-4 7-8 7s-8-3-8-7c0-5 3-9 8-14\"></path></g>",
};
