// Extract the WHO? face part SVGs from the canonical design bundle.
// Reads docs/design/WHO Face System.html, decodes the bundler manifest
// (base64 + gzip), and writes one SVG per part id into the out dir.
// Run: node scripts/extract-faces.mjs <outDir>
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { gunzipSync } from "node:zlib";
import { join } from "node:path";

const HTML = "docs/design/WHO Face System.html";
const outDir = process.argv[2] || "/tmp/who-faces";
mkdirSync(outDir, { recursive: true });

const html = readFileSync(HTML, "utf8");

function block(type) {
  const re = new RegExp(
    `<script type="__bundler/${type}">([\\s\\S]*?)</script>`,
  );
  const m = html.match(re);
  if (!m) throw new Error(`no ${type} block`);
  return JSON.parse(m[1].trim());
}

const manifest = block("manifest");
const extRes = block("ext_resources");

const svg = {}; // id -> full svg text
for (const { id, uuid } of extRes) {
  const entry = manifest[uuid];
  if (!entry) continue;
  if (!/svg/.test(entry.mime)) continue; // only the face SVGs
  if (!/^(eyes|mouth|mark|head)/.test(id)) continue;
  const raw = Buffer.from(entry.data, "base64");
  const bytes = entry.compressed ? gunzipSync(raw) : raw;
  svg[id] = bytes.toString("utf8");
  writeFileSync(join(outDir, `${id}.svg`), bytes);
}

// inner markup between the outer <svg> tags, whitespace-collapsed
const inner = (id) =>
  svg[id]
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>[\s\S]*$/, "")
    .replace(/\s+/g, " ")
    .trim();

const headPath = (svg["head-base"].match(/ d="([^"]+)"/) || [])[1];
const group = (prefix, n) =>
  Array.from({ length: n }, (_, i) => {
    const id = `${prefix}-${String(prefix === "mark" ? i : i + 1).padStart(2, "0")}`;
    return `  ${JSON.stringify(id)}: ${JSON.stringify(inner(id))},`;
  }).join("\n");

const ts = `// AUTO-GENERATED by scripts/extract-faces.mjs from
// "docs/design/WHO Face System.html". Do not edit by hand — re-run the script.
// Each value is the inner SVG markup of a part, drawn ink-on-transparent on the
// shared 0 0 200 200 grid. The head is one path whose fill is set at render time.

export const HEAD_PATH =
  ${JSON.stringify(headPath)};

export const EYES: Record<string, string> = {
${group("eyes", 10)}
};

export const MOUTHS: Record<string, string> = {
${group("mouth", 10)}
};

export const MARKS: Record<string, string> = {
${group("mark", 9)}
};
`;

const tsOut = "components/faces/parts.generated.ts";
mkdirSync("components/faces", { recursive: true });
writeFileSync(tsOut, ts);
console.log(`wrote ${Object.keys(svg).length} svgs to ${outDir}`);
console.log(`wrote ${tsOut}`);
